name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # For DateTime and l10n
  intl: ^0.16.1

  # For Architecture
  flutter_hooks: ^0.14.1
  hooks_riverpod: ^0.12.1

  # For Networking
  dio: ^3.0.10
  dio_http_cache: ^0.2.11

  # For Model
  json_serializable: ^3.5.0
  freezed_annotation: ^0.12.0

  # For Key-Value local storage
  shared_preferences: ^0.5.12+4

  # Convert between Enum and String
  enum_to_string: ^1.0.13

  # For UIs
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.1

  # For Utilities
  get: ^3.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.4

  # For Model
  freezed: ^0.12.2

  # For Analyzer
  effective_dart: ^1.3.0

  # For Testing
  mockito:
  image_test_utils:

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Rotunda
      fonts:
        - asset: assets/fonts/Rotunda-Bold.otf
          weight: 700
